### ISSUE TITLE
add Logistic_Dirty.m and  Logistic_rMTL.m 

### ISSUE THREAD

**Issue by hank9cao** [jiayuzhou/MALSAR#10]
Hi jiayu:

I added the  Logistic_Dirty.m and  Logistic_rMTL.m  in my repo, and they are tested using multiple gene expression data-sets.
Let me know if you want to merge it into your repo.

https://github.com/hank9cao/MALSAR/tree/master/MALSAR/functions/dirty
https://github.com/hank9cao/MALSAR/tree/master/MALSAR/functions/rMTFL

  @jiayuzhou BTW, I noticed you guys want to write the python version of the MALSAR, how did you want to do it? To be honest, MALSAR will get more R users than python users, since R is more common laboratory language across many scientific fields(biology, geography) which are more interested in MALSAR.

Regards,
Hank

**Comment by jiayuzhou** [comment]
@hank9cao It will be great if you could submit a pull request and I will merge it. Do you mind also add corresponding examples? 

I agree that a R package could be very useful. But we are developing a Python version at the moment. We will consider a R implementation after the Python version. Also if you want to start the project sooner, I can also try to help.

**Comment by hank9cao** [comment]
@jiayuzhou Yes, will add it by pull request.
I am quite interested in developing the R version of MALSAR, could you please tell some setup stuff,  big picture or framework, that would be great. Also, I am pleased to get involved in the development of the python version, if possible.

**Comment by huangjinghuangjing** [comment]
周教授，MALSAR的python版您发布了吗？

**Comment by jiayuzhou** [comment]
> 周教授，MALSAR的python版您发布了吗？

Kindly check the link in the paper: https://academic.oup.com/bioinformatics/article-abstract/35/10/1797/5107021?redirectedFrom=fulltext
