### ISSUE TITLE
Cross validation for two parameters

### ISSUE THREAD

**Issue by linanzhang** [jiayuzhou/MALSAR#15]
How to perform cross validation for Least SRMTL, which has two parameters? Thank you.

**Comment by jiayuzhou** [comment]
Check out this example: https://github.com/jiayuzhou/MALSAR/blob/master/examples/train_and_test/CrossValidationDirty.m

**Comment by linanzhang** [comment]
```
obj_func_str = 'Least_SRMTL';
[best_lambda1, best_lambda2, perform_mat] = CrossValidationDirty(X, Y, obj_func_str, obj_func_opts, lambda1_range, lambda2_range, cv_fold, eval_func_str);
```

[.Error using CrossValidationDirty (line 57)
Too many output arguments.

**Comment by jiayuzhou** [comment]
As mentioned above that was an example based on the dirty model, which uses the definition 
`function [W, funcVal, P, Q] = Least_Dirty(X, Y, lambda1, lambda2, opts)`
but the SRMTL uses the following:
`function [W, funcVal] = Least_SRMTL(X, Y, R, rho1, rho2, opts)`

You will need to (hopefully read and) modify your code accordingly.

**Comment by linanzhang** [comment]
Thank you.
