### ISSUE TITLE
Unexpected output dimension 

### ISSUE THREAD

**Issue by linanzhang** [jiayuzhou/MALSAR#16]
Hello, I'm using the sparse graph regularization to learn a model W of size 300 x #tasks. However, I only got 280 rows instead of 300. I'm guessing that some function removes rows of NaN in some step. Please confirm my conjecture. And is there a way to track which rows are removed? Thanks.

**Comment by jiayuzhou** [comment]
I think it may have something to do with the data input. The W is initialized before running the algorithms. See for example:

https://github.com/jiayuzhou/MALSAR/blob/master/MALSAR/functions/SRMTL/Least_SRMTL.m#L83

Let me know what do you find.

**Comment by linanzhang** [comment]
I sort of figured out. Even though I ran different experiments on different computers on the server, it seems that "addpath" messed up the path with the correct input files.
