### ISSUE TITLE
Undefined function or variable 'eplb'.

### ISSUE THREAD

**Issue by FreakChan** [jiayuzhou/MALSAR#17]
Excellent work!
When i performed MALSAR/functions/sparse_low_rank/Least_SpareTrace.m, I found a missing function.

```
Undefined function or variable 'eplb'.

Error in Least_SparseTrace (line 171)
        [s_hat, lambda_new ]=eplb(s_bar, size(s_bar, 1), tau, lambda_old);
```

I look around the MALSAR file, and I can't find that function.
Can you provide that function? or tell me how to solve that problem.
Thank you so much!
Excellent work again! i'm so admire.

**Comment by jiayuzhou** [comment]
`eplb` is a C function that you will need to compile it (depending on your computer), I had precompiled binaries for Windows and Mac. See: 
https://github.com/jiayuzhou/MALSAR/tree/master/MALSAR/c_files/eplb
